### ISSUE TITLE
sometimes nsqadmin becomes unaware of topic

### ISSUE THREAD

**Issue by Dieterbe** [bitly/nsq#637] opened 2015-08-17 11:28 UTC
i have a producer, and a consumer, using the "metrics" topic.
sometimes nsqadmin becomes unaware of the metrics topic.  i've seen this in 2 scenarios:
* when the consumer was down for a while, and i bring it back up
* if the producer sends a larger than usual volume of messages

![huh-where-did-topic-go](https://cloud.githubusercontent.com/assets/20774/9303958/6a9a30fc-44e3-11e5-9220-e038c1620488.png)

that said, i can prove that all messages safely made it across (from producer to consumer),
but it's annoying that sometimes the admin UI is not aware, especially when it initially was.

or could this perhaps be caused by something like the producer/consumer backing up for a bit?

btw this is with `/nsqadmin --nsqd-http-address=nsqd:4151`, no nsqlookup daemon.

**Comment by jehiah** [comment] 2015-08-17 11:39
@Dieterbe This generally indicates nsqadmin timed out it's call to nsqd because one or the other was resource starved and didn't respond quick enough. We have captured in #421 the need for that type of error to be surfaced in the UI (Which we have been steadily working towards). 

Do you have any logs from nsqadmin that could confirm if this is a duplicate of that issue?

**Comment by Dieterbe** [comment] 2015-08-17 14:10
yep. seeing
```
2015/08/17 14:10:30 NSQD: querying http://nsqd:4151/stats?format=json
2015/08/17 14:10:30 NSQD: querying http://nsqd:4151/stats?format=json
2015/08/17 14:10:32 ERROR: lookupd http://nsqd:4151/stats?format=json - Get http://nsqd:4151/stats?format=json: read tcp 172.17.0.38:4151: i/o timeout
```

**Comment by jehiah** [comment] 2015-08-17 14:11
Thanks for confirming. closing in favor of #421 then

**Closed by jehiah** 2015-08-17 14:11 UTC
