### ISSUE TITLE
docker: scratch vs. busybox

### ISSUE THREAD

**Issue by saidimu** [bitly/nsq#543] opened 2015-02-18 20:47 UTC
Unlike the [deprecated images] (https://registry.hub.docker.com/u/nsqio/nsqd/), the official image [`nsqio/nsq`] (https://registry.hub.docker.com/u/nsqio/nsq/) isn't an Automated Build.

**Comment by mreiferson** [comment] 2015-02-18 21:03
Hi @saidimu - can you elaborate?  This was an intentional design decision because the old way we were doing things was broken.

The other benefit with the new approach is that the images are an order of magnitude smaller.

See https://github.com/bitly/nsq/pull/534 and relates issues it links to for more context.

**Comment by mreiferson** [comment] 2015-02-18 21:03
cc @paddyforan

**Comment by saidimu** [comment] 2015-02-18 21:41
The dramatically smaller images are super awesome, even with the loss of auto-discovery of `nsqd` host ips (previously I relied on `hostname --ip` to auto set the `--broadcast-address` flag). For now I'll stick to the deprecated images until I figure out another approach.

The deprecated images were linked to the Github repo so users could easily inspect the [Dockerfile](https://registry.hub.docker.com/u/nsqio/nsqd/dockerfile/) and be certain of the source of the image. Additional [build details](https://registry.hub.docker.com/u/nsqio/nsqd/builds_history/41603/) were also displayed; this was useful when deciding whether to pull updated images.

All that meta-data is lost with the new images because they aren't setup to automatically build on Github repo pushes.

AFAIK setting up an [automated build] (https://docs.docker.com/docker-hub/builds/) won't interfere with the new images.

**Comment by paddyforan** [comment] 2015-02-18 21:51
@saidimu couple of issues here:

1. No auto-discovery. This is a really annoying loss, and something I'm very interested in fixing. The complication is that all the binaries are in the same image. An obvious solution is to just expose the ports for all the binaries on the image, which would (I think) fix the auto discovery problem.
2. The loss of metadata in Docker Hub can be offset by updating the description on Docker Hub, can it not? Or am I not understanding? The build details you link to are just the timestamps and resulting image IDs of the builds. I'm struggling to find a use case for this information, considering (as far as I know) @mreiferson does not make a practice of updating old versions after they're released, opting instead to increment the version number, which would result in a new timestamped release, with a changelog, and links to the commits that changed between that release and the previous. That seems much more useful, right?
3. "But why can't you just have an automated build anyways?" To achieve that, we need to bundle the entire build environment and all the source code into the Docker image. That results in a huge, 700 MB Docker image. What we're doing instead is bundling the binaries into a minimal Docker image. This requires a build step, however, and Automated Builds on Docker don't support build steps. Everything must be accomplished in the Dockerfile, which means everything ends up as part of the image. We can't have an automated build because we need that step between the repository being pulled and "docker build" being run.

Does this clear things up?

**Comment by mreiferson** [comment] 2015-02-18 23:42
Can someone elaborate on what y'all mean by "auto discovery"?

**Comment by paddyforan** [comment] 2015-02-18 23:58
_I'm_ talking about making it possible to have Docker automatically assign a port for, e.g., nsqd from the available ports on the host, and easily and programmatically being able to get an IP and port for that container. Which, right now, is not possible--you have to do the port mapping manually. Rereading @saidimu's comment, they may be talking about something different, in which case, they'll have to clarify. :)

**Comment by saidimu** [comment] 2015-02-19 00:23
Much clearer, thanks.

1. Exposing the ports on the host will work but is not portable (it assumes those ports are always available) and is also slightly less secure than Docker linking since the ports are exposed externally on the host. Without basic bash tools, auto-discovery seems impossible without adding it into `nsqd` itself.

2. Automated builds used to be called trusted builds as their initial function was to provide proof of the Dockerfile and sources that generated the image.

3. There are ways of getting automated builds without a massive Docker image but they all involve a few steps that may not be worth the hassle.

At this point auto-discovery seems a more urgent issue.

**Comment by paddyforan** [comment] 2015-02-19 00:24
Reading through, my guess is actually that I'm talking about something different, and @saidimu is talking about being able to use the `hostname` command to return the IP of the container for use in the `broadcast-address`. Because our container no longer has a linux distro on it, that no longer works. I'm not sure why using the Docker IP address (assigned to `docker0` on the host) is not an option, however.

```bash
docker@boot2docker:~$ ifconfig | grep "docker0" -C 1
docker0   Link encap:Ethernet  HWaddr 56:84:7A:FE:97:99
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
docker@boot2docker:~$ docker run -d -p 4151:4151 nsqio/nsq /nsqd --broadcast-address=172.17.42.1
503d8df6072d8f0d6a389a0819c1b016b328b755ec0a8b9226e8870f054de5b9
docker@boot2docker:~$ curl http://172.17.42.1:4151/ping
OK
```

**Comment by saidimu** [comment] 2015-02-19 00:27
@paddyforan That's exactly what I meant by auto-discovery :)
@mreiferson The docs on running the Docker image involve manually specifying the host's IP.

**Comment by paddyforan** [comment] 2015-02-19 00:30
1. If it's used with `-P`, not `-p`, the ports are auto-assigned to the host. You can then get the port using `docker port <container id>`.
    > First, you can supply -P or --publish-all=true|false to docker run which is a blanket operation that identifies every port with an EXPOSE line in the image's Dockerfile and maps it to a host port somewhere in the range 49153–65535. This tends to be a bit inconvenient, since you then have to run other docker sub-commands to learn which external port a given service was mapped to.

2. If you don't trust the docker image, you can always build your own by running `dist.sh`.
3. I can think of a few, but they all have infrastructure costs, cause problems with building locally, and are otherwise problematic.

**Comment by saidimu** [comment] 2015-02-19 00:41
@paddyforan `docker0' only works in the way you specified if the containers expose ports to the host. If you use Docker linking (to minimize port clashing, etc) then it doesn't work. That is where `hostname` comes in handy to auto-discover the container's IP.

**Comment by paddyforan** [comment] 2015-02-19 00:47
Hmm. I think I understand what you're saying, but the documentation doesn't say anything about that restriction, as far as I can tell. Let me run a couple tests and I can either show you a working implementation, we'll have a reproduced bug and may be able to do something about it for v0.3.3.

**Comment by paddyforan** [comment] 2015-02-19 01:25
So here's what I'm discovering:

1. If you don't specify a `--broadcast-address`, `nsqd` defaults to the result of `os.Hostname()`. Which a small test tells me is the short ID of the container. So that's probably not what we want.
2. The best way to specify a `lookupd-tcp-address` from dynamically assigned ports can't take advantage of the environment variables exposed by linking containers, which would be nice. If we expand environment variables in the options, that would make it dead simple if you're running nsqlookupd and nsqd linked together.
3. It appears to work just fine to use dynamically assigned ports (I used a modified Dockerfile to EXPOSE the ports):

```
$ docker run --name lookupd -P -d nsq /nsqlookupd
$ docker port lookupd
4150/tcp -> 0.0.0.0:49156
4151/tcp -> 0.0.0.0:49157
4160/tcp -> 0.0.0.0:49158
4161/tcp -> 0.0.0.0:49153
4170/tcp -> 0.0.0.0:49154
4171/tcp -> 0.0.0.0:49155
$ docker run --name nsqd --link lookupd:lookupd -P nsq /nsqd --lookupd-tcp-address=172.17.42.1:49158
```

At least, the nsqd (I started two) and the nsqlookupd seem to be able to exchange heartbeats correctly.

```
$ curl http://172.17.42.1:49153/nodes
{"status_code":200,"status_txt":"OK","data":{"producers":[{"remote_address":"172.17.42.1:53333","hostname":"2648a6c4984a","broadcast_address":"2648a6c4984a","tcp_port":4150,"http_port":4151,"version":"0.3.2-alpha","tombstones":[],"topics":[]},{"remote_address":"172.17.42.1:53335","hostname":"72f6d1815c44","broadcast_address":"72f6d1815c44","tcp_port":4150,"http_port":4151,"version":"0.3.2-alpha","tombstones":[],"topics":[]}]}}
```

So I think (@mreiferson, my `broadcast-address` usage knowledge is fuzzy, so correct me if I'm wrong here) you can just set 172.17.42.1 as the broadcast address, and things will work just fine once we get the ports listed as "EXPOSE"d. If @mreiferson wants to hop in with a bit more information on how broadcast-address is used, especially in multi-tenant situations, I could be more sure.

But we could make the use case for linking easier by accepting and expanding environment variables when setting the addresses to look for services, especially for things like nsq_to_file, etc, So that may be something worth looking into. The [os.ExpandEnv](http://golang.org/pkg/os/#ExpandEnv) function could probably make that a pretty small PR.

**Comment by saidimu** [comment] 2015-02-19 02:02
@paddyforan You're correct about not specifying `--broadcast-address`. It doesn't work because the container IDs cannot be resolved to the container IP. Would be great if Docker supported this.

With the deprecated images, I dynamically assigned ports and took advantage of environment vars by setting the containter entrypoint to `/bin/bash` and setting the container command to something like

```-c nsqd --broadcast-address=`hostname --ip` --lookupd-tcp-address=$NSQLOOKUPD_1```

Assuming one is comfortable with exposing ports on the host, setting `--broadcast-address` to `172.17.42.1` is not advised because Docker's subnet assignment at startup may pick a different address range. Setting it to `docker0` may work since that interface name is more stable.

For the cases where exposing container ports on the host is not an option, expanding env vars is probably the only way. I'm not comfortable in Go else I'd have submitted a PR.

**Comment by paddyforan** [comment] 2015-02-19 02:34
```
$ docker run --name lookupd nsqbusybox /bin/sh -c '/nsqlookupd --broadcast-address=`hostname -i`'
[nsqlookupd] 2015/02/19 02:29:13.752069 nsqlookupd v0.3.2-alpha (built w/go1.4)
[nsqlookupd] 2015/02/19 02:29:13.752345 TCP: listening on [::]:4160
[nsqlookupd] 2015/02/19 02:29:13.752456 HTTP: listening on [::]:4161
[nsqlookupd] 2015/02/19 02:29:30.532943 TCP: new client(172.17.0.17:49609)
[nsqlookupd] 2015/02/19 02:29:30.533547 CLIENT(172.17.0.17:49609): desired protocol magic '  V1'
[nsqlookupd] 2015/02/19 02:29:30.535064 CLIENT(172.17.0.17:49609): IDENTIFY Address:86e61aabcc74 TCP:4150 HTTP:4151 Version:0.3.2-alpha
[nsqlookupd] 2015/02/19 02:29:30.535170 DB: client(172.17.0.17:49609) REGISTER category:client key: subkey:
[nsqlookupd] 2015/02/19 02:29:45.542774 CLIENT(172.17.0.17:49609): pinged (last ping 15.007718549s)
```

```
$ docker run --link lookupd:lookupd nsqbusybox /bin/sh -c '/nsqd --lookupd-tcp-address=$LOOKUPD_PORT_4160_TCP_ADDR:$LOOKUPD_PORT_4160_TCP_PORT'
[nsqd] 2015/02/19 02:29:30.521893 nsqd v0.3.2-alpha (built w/go1.4)
[nsqd] 2015/02/19 02:29:30.521964 ID: 748
[nsqd] 2015/02/19 02:29:30.522008 NSQ: persisting topic/channel metadata to nsqd.748.dat
[nsqd] 2015/02/19 02:29:30.532386 LOOKUP: adding peer 172.17.0.16:4160
[nsqd] 2015/02/19 02:29:30.532462 LOOKUP connecting to 172.17.0.16:4160
[nsqd] 2015/02/19 02:29:30.532796 TCP: listening on [::]:4150
[nsqd] 2015/02/19 02:29:30.532914 HTTP: listening on [::]:4151
[nsqd] 2015/02/19 02:29:30.536774 LOOKUPD(172.17.0.16:4160): peer info {TcpPort:4160 HttpPort:4161 Version:0.3.2-alpha BroadcastAddress:172.17.0.16}
[nsqd] 2015/02/19 02:29:45.539808 LOOKUPD(172.17.0.16:4160): sending heartbeat
```

Does that look like what you want?

There's a size cost, but it's negligible.

```
$ docker images nsqbusybox
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nsqbusybox          latest              5a9c99ebd3ff        23 minutes ago      79.44 MB
$ docker images nsqio/nsq
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nsqio/nsq           latest              6b9ced78812f        10 days ago         76.73 MB
```

/cc @MDrollette, who, last I recall, was interested in the `FROM scratch` vs. `FROM busybox` distinction. `FROM busybox` certainly gives us some nice auto assignment without changing the application at all.

**Comment by saidimu** [comment] 2015-02-19 03:37
`FROM busybox ` works pretty much like the deprecated images with a ~10x size reduction. Shell expansion FTW!

**Comment by paddyforan** [comment] 2015-02-19 03:39
That demo was using `FROM busybox` :)

**Comment by saidimu** [comment] 2015-02-19 03:44
Yeah. It is awesome that it provides basic shell tools in a small box.

**Comment by paddyforan** [comment] 2015-02-19 03:46
I just know we discussed using `busybox`, and people were against it for some reason, but I can't recall what exactly. So I'm going to let them chime in here.

**Comment by saidimu** [comment] 2015-02-19 03:52
I'm curious to hear why they were against it. Seems like `FROM scratch` is for severely-constrained resource environments like embedded devices, routers and the like.

**Comment by paddyforan** [comment] 2015-02-19 03:59
Found it. Came up in IRC conversation, so I pinged @MDrollette unnecessarily. Oops.

https://github.com/bitly/nsq/issues/528#issuecomment-71095982

"Against it" is probably too strong a way of phrasing it. Sounds like it was just considered unnecessary, though this may be a good argument to include it.

@mreiferson thoughts? The main benefit is that you can reuse a startup script across hosts without worrying about the `broadcast-address` or port usage/mapping. Incidentally, you also get the same shell expansion that you've always had, but which we lost in the last images. The upgrade should be transparent to 99.99% of users. The only people I can think of who will be inconvenienced are those that pinned the base image, too. And even that shouldn't break anything, I think. We'd be able to accomplish this with a couple lines of changes in the Dockerfile, and it could go out with the next release.

**Comment by saidimu** [comment] 2015-02-19 04:11
:+1:

**Comment by mreiferson** [comment] 2015-02-19 05:23
Yea, switching to `busybox` sounds like a good path forward - thanks @saidimu & @paddyforan

**Comment by mreiferson** [comment] 2015-02-19 20:45
anyone want to volunteer to open the PR?

**Comment by paddyforan** [comment] 2015-02-19 22:03
I'll send it when I fix that dist.sh bug so that the image is tagged as latest, too. Sound good? I can open a PR in a few hours, I think.

**Comment by mreiferson** [comment] 2015-02-19 22:10
thanks as always @paddyforan :heart:

**Comment by paddyforan** [comment] 2015-02-19 22:12
I just want to make sure that the upgrade is seamless, so the old `docker run nsqio/nsq /nsqd` continues to work, as well as the new shell expansion stuff.

**Closed** 2015-02-20 15:35 UTC
Labels: question

**Comment by ankitathakur** [comment] 2016-06-23 14:45
I've a query : "Docker doesn’t have the need to expose ports to link containers" -- does this mean that the containers are more secure or it implies that the containers are less secure? Please suggest.

**Comment by ankitathakur** [comment] 2016-06-23 14:53
I've a query. Can anyone please explain me what does the following statement mean:

"Docker doesn’t have the need to expose ports to link containers" 

Does this imply that containers are "highly secured" or it mean it's "less secured" ?
